// Generated by CoffeeScript 1.6.3
(function() {
  define(["backend/equationIndex"], function(equationIndex) {
    var solveEquation;
    return solveEquation = function(equationID, variable) {
      var equation;
      equation = equationIndex.get(equationID);
      return equation.solve(variable);
    };
  });

}).call(this);
