// Generated by CoffeeScript 1.6.3
(function() {
  define(function() {
    var uncertainties;
    uncertainties = {};
    return {
      set: function(variable, uncertainty) {
        return uncertainties[variable] = uncertainty;
      },
      get: function(variable) {
        if (variable in uncertainties) {
          return uncertainties[variable];
        } else {
          return null;
        }
      },
      getExpression: function(variable) {
        return uncertaintyExpressions[variable];
      },
      getUncertaintyMap: function() {
        return uncertainties;
      },
      clear: function() {
        var prop, _results;
        _results = [];
        for (prop in uncertainties) {
          if (uncertainties.hasOwnProperty(prop)) {
            _results.push(delete uncertainties[prop]);
          } else {
            _results.push(void 0);
          }
        }
        return _results;
      }
    };
  });

}).call(this);
