// Generated by CoffeeScript 1.6.3
(function() {
  define(["backend/equationIndex", "backend/equivalenciesIndex", "backend/expressionIndex", "backend/numericalValues", "backend/uncertaintiesIndex", "backend/variableIndex"], function(equationIndex, equivalenciesIndex, expressionIndex, numericalValues, uncertaintiesIndex, variableIndex) {
    return function() {};
  });

}).call(this);
