// Generated by CoffeeScript 1.6.3
(function() {
  var $, setDraggables;

  $ = jQuery;

  $(document).ready(function() {
    return setDraggables();
  });

  setDraggables = function() {
    var draggableProperties;
    draggableProperties = {
      containment: "#whiteboard-panel",
      scroll: false,
      cancel: ".variable"
    };
    $(".equation").draggable(draggableProperties);
    return $(".expression").draggable(draggableProperties);
  };

}).call(this);
