// Generated by CoffeeScript 1.6.3
(function() {
  define(["jquery", "frontend/setEventHandlers", "frontend/connections", "frontend/updateSearchResults", "frontend/setExtraEventHandlers"], function($, setEventHandlers, connections, updateSearchResults, setExtraEventHandlers) {
    return function() {
      $(window).resize(function() {
        return connections.repaintVariables();
      });
      setEventHandlers();
      updateSearchResults();
      return setExtraEventHandlers();
    };
  });

}).call(this);
