// Generated by CoffeeScript 1.6.3
(function() {
  define(["jquery", "frontend/rewrite", "backend/substituteEquation", "backend/equationIndex", "backend/expressionIndex", "frontend/addExpression"], function($, rewrite, substituteEquation, equationIndex, expressionIndex, addExpression) {
    return function(targetExpressionID, sourceEquationID, variableID) {
      var expression, sourceEquation, subbedEquations, targetExpression, _i, _len, _ref, _results;
      targetExpression = expressionIndex.get(targetExpressionID);
      sourceEquation = equationIndex.get(sourceEquationID);
      subbedEquations = substituteEquation(targetExpression, sourceEquation, variableID);
      rewrite.rewriteExpression(targetExpressionID, subbedEquations[0]);
      _ref = subbedEquations.slice(1);
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        expression = _ref[_i];
        _results.push(addExpression(expression));
      }
      return _results;
    };
  });

}).call(this);
