// Generated by CoffeeScript 1.6.3
(function() {
  define(["jquery", "index", "render", "eventHandler"], function($, index, render, eventHandler) {
    var addEquation, placeRandomly;
    placeRandomly = function(element) {
      var eH, eL, eT, eW, left, top, wH, wL, wT, wW;
      wT = $("#whiteboard").offset().top;
      wL = $("#whiteboard").offset().left;
      wH = $("#whiteboard").height();
      wW = $("#whiteboard").width();
      eT = element.offset().top;
      eL = element.offset().left;
      eH = element.height();
      eW = element.width();
      top = (Math.random() * (wH - eH) - eT) / wH * 100;
      left = (Math.random() * (wW - eW) - eL) / wL * 100;
      return element.css({
        top: top + "%",
        left: left + "%"
      });
    };
    addEquation = function(equation) {
      $("#whiteboard").append(equation.element);
      index.equation.add(equation);
      equation.element.attr("id", "equation-" + equation.id);
      return render.math(function() {
        equation.element = $("#equation-" + equation.id);
        eventHandler.equation(equation.element);
        return placeRandomly(equation.element);
      });
    };
    return addEquation;
  });

}).call(this);
