// Generated by CoffeeScript 1.6.3
(function() {
  define(["jquery", "index", "render", "eventHandler"], function($, index, render, eventHandler) {
    var addExpression;
    addExpression = function(expression) {
      $("#whiteboard").append(expression.element);
      index.expression.add(expression);
      expression.element.attr("id", "expression-" + expression.id);
      return render.math(function() {
        expression.element = $("#expression-" + expression.id);
        return eventHandler.expression(expression.element);
      });
    };
    return addExpression;
  });

}).call(this);
