// Generated by CoffeeScript 1.6.3
(function() {
  define(["jquery", "index", "render", "eventHandler"], function($, index, render, eventHandler) {
    var addEquation, placeRandomly;
    placeRandomly = function(element) {
      var eH, eL, eT, eW, left, top, wH, wL, wT, wW;
      wT = $("#whiteboard").offset().top;
      wL = $("#whiteboard").offset().left;
      wH = $("#whiteboard").height();
      wW = $("#whiteboard").width();
      eT = element.offset().top;
      eL = element.offset().left;
      eH = element.height();
      eW = element.width();
      top = (Math.random() * (wH - eH) - eT) / wH * 100;
      left = (Math.random() * (wW - eW) - eL) / wW * 100;
      return element.css({
        top: top + "%",
        left: left + "%"
      });
    };
    addEquation = function(equation) {
      $("#whiteboard").append(equation.element);
      equation.element.attr("id", "equation-" + equation.id);
      return render.math(function() {
        var label, variable, _i, _len, _ref, _results;
        equation.element = $("#equation-" + equation.id);
        eventHandler.equation(equation.element);
        placeRandomly(equation.element);
        _ref = equation.element.find(".variable");
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          variable = _ref[_i];
          label = $(variable).text();
          _results.push($(variable).attr("id", "variable-equ-" + equation.id + "-" + label));
        }
        return _results;
      });
    };
    return addEquation;
  });

}).call(this);
