// Generated by CoffeeScript 1.7.1
(function() {
  define(["jquery", "index", "render", "eventHandler"], function($, index, render, eventHandler) {
    var addEquation;
    addEquation = function(equation) {
      $("#whiteboard").append(equation.element);
      index.equation.add(equation);
      equation.element.attr("id", "equation-" + equation.id);
      return render.math(function() {
        var elH, elW, left, top, wH, wW;
        equation.element = $("#equation-" + equation.id);
        eventHandler.equation(equation.element);
        elW = equation.element.width();
        elH = equation.element.height();
        wW = $("#whiteboard").width();
        wH = $("#whiteboard").height();
        left = Math.random() * ((wW - elW) / wW) * 100;
        console.log(left);
        top = Math.random() * ((wH - elH) / wH) * 100;
        equation.element.css("position", "absolute");
        equation.element.css("left", "" + left + "%");
        return equation.element.css("top", "" + top + "%");
      });
    };
    return addEquation;
  });

}).call(this);
