// Generated by CoffeeScript 1.7.1
(function() {
  define(["jquery"], function($) {
    var draggableProperties, equation, expression;
    draggableProperties = {
      containment: "#whiteboard",
      scroll: false,
      cancel: ".variable",
      drag: function(event, ui) {},
      stop: function(event, ui) {
        $(this).css("left", "" + (parseInt($(this).css("left")) / ($("#whiteboard").width() / 100)) + "%");
        return $(this).css("top", "" + (parseInt($(this).css("top")) / ($("#whiteboard").height() / 100)) + "%");
      }
    };
    equation = function(element) {
      return element.draggable(draggableProperties);
    };
    expression = function(element) {
      return element.draggable(draggableProperties);
    };
    return {
      equation: equation,
      expression: expression
    };
  });

}).call(this);
