// Generated by CoffeeScript 1.6.3
(function() {
  define(["jquery"], function($) {
    var draggableProperties, equation, expression, mousedownHandler, mouseupHandler;
    draggableProperties = {
      containment: "#whiteboard",
      scroll: false,
      cancel: ".variable",
      start: function(event, ui) {},
      drag: function(event, ui) {},
      stop: function(event, ui) {
        $(this).css("left", "" + (parseInt($(this).css("left")) / ($("#whiteboard").width() / 100)) + "%");
        return $(this).css("top", "" + (parseInt($(this).css("top")) / ($("#whiteboard").height() / 100)) + "%");
      }
    };
    mousedownHandler = function(event) {
      return $(event.target).css("cursor", "grabbing");
    };
    mouseupHandler = function(event) {
      return $(event.target).css("cursor", "grab");
    };
    equation = function(element) {
      element.draggable(draggableProperties);
      element.mousedown(mousedownHandler);
      return element.mouseup(mouseupHandler);
    };
    expression = function(element) {
      element.draggable(draggableProperties);
      element.mousedown(mousedownHandler);
      return element.mouseup(mouseupHandler);
    };
    return {
      equation: equation,
      expression: expression
    };
  });

}).call(this);
