// Generated by CoffeeScript 1.6.3
(function() {
  define(["coffeequate", "elementTools", "index"], function(CQ, elementTools, index) {
    var Expression;
    return Expression = (function() {
      function Expression(lhs, rhs) {
        this.lhs = CQ(lhs);
        this.rhs = CQ(rhs);
        index.expression.add(this);
        this.element = elementTools.makeExpression(this.toMathML());
      }

      Expression.prototype.toMathML = function() {
        return "<mrow>" + (this.lhs.toMathML()) + "<mo>=</mo>" + (this.rhs.toMathML()) + "</mrow>";
      };

      return Expression;

    })();
  });

}).call(this);
