// Generated by CoffeeScript 1.6.3
/*
Graphical Equation Manipulator

Matthew Alger, based on Buck Shlegeris' pyGEM.
https://github.com/MatthewJA/Graphical-Equation-Manipulator
https://github.com/bshlgrs/pyGEM

Licensed under GPL v3.
*/


(function() {
  require.config({
    baseUrl: "./src",
    paths: {
      jquery: "vendor/jquery-2.1.1.min",
      coffeequate: "vendor/coffeequate.min",
      mathjax: "http://cdn.mathjax.org/mathjax/latest/" + "MathJax.js?config=MML_HTMLorMML.js",
      jqueryui: "vendor/jquery-ui.min"
    },
    shim: {
      jqueryui: ["jquery"],
      mathjax: {
        exports: "MathJax",
        init: function() {
          MathJax.Hub.Config({
            config: ["MMLorHTML.js"],
            jax: ["input/MathML", "output/HTML-CSS"],
            extensions: ["mml2jax.js", "MathMenu.js", "MathZoom.js"],
            showMathMenu: false,
            showMathMenuMSIE: false
          });
          MathJax.Hub.Startup.onload();
          return MathJax;
        }
      }
    }
  });

  require(["jquery", "Expression", "render", "jqueryui", "search"], function($, Expression, render, ui, search) {
    var canvas, resizeTimer;
    window.gem.loaded = true;
    canvas = $("#lines-canvas")[0];
    resizeTimer = null;
    window.gem.updateCanvasSize = function() {
      var height, width;
      width = $("#whiteboard").width();
      height = $("#whiteboard").height();
      canvas.width = width;
      canvas.height = height;
      return require(["redrawCanvas"], function(redrawCanvas) {
        return redrawCanvas();
      });
    };
    $(window).resize(function() {
      clearTimeout(resizeTimer);
      return resizeTimer = setTimeout(window.gem.updateCanvasSize, 50);
    });
    search.setup();
    return require(["addEquation", "addExpression", "formulae", "Line", "index", "search"], function(addEquation, addExpression, formulae, Line, index, search) {
      var fs;
      addEquation(formulae.getEquation("angular-momentum", true));
      addEquation(formulae.getEquation("momentum", true));
      addEquation(formulae.getEquation("torque", true));
      addEquation(formulae.getEquation("force", true));
      fs = formulae.getAllFormulaNames();
      search.drawFormulae(fs);
      return window.fs = search.formulaSearch;
    });
  });

}).call(this);
