// Generated by CoffeeScript 1.6.3
(function() {
  MathJax.Hub.Config({
    config: ["MMLorHTML.js"],
    jax: ["input/MathML", "output/HTML-CSS"],
    extensions: ["mml2jax.js", "MathMenu.js", "MathZoom.js"],
    showMathMenu: false,
    showMathMenuMSIE: false
  });

  require.config({
    paths: {
      "jquery": "lib/jquery.min",
      "jqueryui": "lib/jquery-ui.min",
      "JSAlgebra": "lib/JS-Algebra/src/",
      "MathJax": "http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=MML_HTMLorMML",
      "TouchPunch": "lib/Touch-Punch/jquery.ui.touch-punch.min"
    },
    shim: {
      "jqueryui": ["jquery"],
      "TouchPunch": ["jquery"]
    }
  });

  require(["jquery", "jqueryui", "TouchPunch", "frontend/setupFrontend", "frontend/finishLoading"], function($, ui, tp, setupFrontend, finishLoading) {
    return $(function() {
      setupFrontend();
      return finishLoading();
    });
  });

}).call(this);
