// Generated by CoffeeScript 1.6.3
(function() {
  define(function() {
    var equation, expression;
    equation = (function() {
      var add, equations, get, getRawEquations;
      equations = [];
      add = function(equation) {
        equation.id = equations.length;
        return equations.push(equation);
      };
      get = function(id) {
        return equations[id];
      };
      getRawEquations = function() {
        return equations;
      };
      return {
        add: add,
        get: get,
        getRaw: getRawEquations
      };
    }).call();
    expression = (function() {
      var add, expressions, get, getRawExpressions;
      expressions = [];
      add = function(expression) {
        expression.id = expressions.length;
        return expressions.push(expression);
      };
      get = function(id) {
        return expressions[id];
      };
      getRawExpressions = function() {
        return expressions;
      };
      return {
        add: add,
        get: get,
        getRaw: getRawExpressions
      };
    }).call();
    return {
      equation: equation,
      expression: expression
    };
  });

}).call(this);
