// Generated by CoffeeScript 1.6.3
(function() {
  define([], function() {
    var Line;
    Line = (function() {
      function Line(a, b) {
        this.a = a;
        this.b = b;
      }

      Line.prototype.startPosition = function() {
        var height, offset, width;
        offset = this.a.offset();
        width = this.a.width();
        height = this.a.height();
        return [offset.left - width / 2, offset.top];
      };

      Line.prototype.endPosition = function() {
        var height, offset, width;
        offset = this.b.offset();
        width = this.b.width();
        height = this.b.height();
        return [offset.left - width / 2, offset.top];
      };

      Line.prototype.draw = function(context) {
        if (context.setLineDash != null) {
          context.setLineDash([5]);
        } else {
          context.mozDash([5]);
          context.webkitLineDash = [5];
        }
        context.strokeStyle = "#AAAAAA";
        context.beginPath();
        context.moveTo.apply(context, this.startPosition());
        context.lineTo.apply(context, this.endPosition());
        return context.stroke();
      };

      return Line;

    })();
    return Line;
  });

}).call(this);
