// Generated by CoffeeScript 1.6.3
(function() {
  define(["index"], function(index) {
    return function() {
      var context;
      context = $("#lines-canvas")[0].getContext("2d");
      context.clearRect(0, 0, context.canvas.width, context.canvas.height);
      return index.line.redrawAll(context);
    };
  });

}).call(this);
