// Generated by CoffeeScript 1.7.1
(function() {
  define(["mathjax"], function(MathJax) {
    var math;
    math = function(callback) {
      MathJax.Hub.Queue(["Typeset", MathJax.Hub]);
      return MathJax.Hub.Queue(callback);
    };
    return {
      math: math
    };
  });

}).call(this);
