// Generated by CoffeeScript 1.6.3
(function() {
  define(["jquery"], function($) {
    var setupFrontend;
    return setupFrontend = function() {
      var setDraggables;
      setDraggables = function() {
        var draggableProperties;
        draggableProperties = {
          containment: "#whiteboard-panel",
          scroll: false,
          cancel: ".variable"
        };
        $(".equation").draggable(draggableProperties);
        return $(".expression").draggable(draggableProperties);
      };
      return setDraggables();
    };
  });

}).call(this);
