// Generated by CoffeeScript 1.6.3
/*
CLASSES
*/


(function() {
  var Snake, draw, getMainLoop, start, update, updateCanvasSize;

  Snake = (function() {
    function Snake(x, y) {
      this.x = x;
      this.y = y;
      this.d = 0;
      this.v = 0.00025;
      this.targetR = 11;
      this.r = this.targetR;
      this.dr = 2;
      this.x0 = this.x - this.radius();
      this.y0 = this.y;
      this.colour = {
        snake: "#EFEFEF",
        debug: "#444444"
      };
      this.width = 0.015;
    }

    Snake.prototype.radius = function() {
      return Math.abs(1 / this.r);
    };

    Snake.prototype.move = function(dt) {
      this.updateRadius(dt);
      console.log(this.v / this.radius());
      this.d = (this.d + this.v / this.radius() * dt) % (2 * Math.PI);
      this.x = this.radius() * Math.cos(this.d) + this.x0;
      return this.y = this.radius() * Math.sin(this.d) + this.y0;
    };

    Snake.prototype.updateRadius = function(dt) {
      var k, r, x1, y1;
      if (this.r === this.targetR) {
        return;
      }
      r = (this.r * 4 + this.targetR) / 5;
      if (this.r < 0 && r > 0) {
        k = this.r / Math.abs(r);
      } else if (this.r > 0 && r < 0) {
        k = Math.abs(this.r) / r;
      } else {
        k = this.r / r;
      }
      x1 = k * (this.x0 - this.x) + this.x;
      y1 = k * (this.y0 - this.y) + this.y;
      if ((r < 0 && this.r > 0) || (r > 0 && this.r < 0)) {
        this.d = (this.d + Math.PI) % (2 * Math.PI);
        this.v = -this.v;
      }
      this.r = r;
      this.x0 = x1;
      return this.y0 = y1;
    };

    Snake.prototype.turn = function(direction) {
      return this.targetR = this.r - this.dr * direction;
    };

    Snake.prototype.draw = function(context) {
      var size;
      size = context.canvas.width;
      context.lineWidth = this.width / 10 * size;
      context.strokeStyle = this.colour.debug;
      context.fillStyle = this.colour.debug;
      context.beginPath();
      context.arc(this.x0 * size, this.y0 * size, this.width * size / 4, 0, 2 * Math.PI);
      context.closePath();
      context.fill();
      context.beginPath();
      context.arc(this.x0 * size, this.y0 * size, this.radius() * size, 0, 2 * Math.PI);
      context.closePath();
      context.stroke();
      context.fillStyle = this.colour.snake;
      context.beginPath();
      context.arc(this.x * size, this.y * size, this.width * size, 0, 2 * Math.PI);
      context.closePath();
      return context.fill();
    };

    Snake.prototype.handleKeyPress = function(key) {
      switch (key) {
        case 37:
        case 65:
          return this.turn(1);
        case 39:
        case 68:
          return this.turn(-1);
      }
    };

    return Snake;

  })();

  /*
  HELPER FUNCTIONS
  */


  /*
  MAIN FUNCTIONS
  */


  updateCanvasSize = function(canvas, context) {
    var height, width;
    height = Math.min(window.innerHeight, window.innerWidth);
    width = height;
    canvas.style.width = "" + width + "px";
    canvas.style.height = "" + height + "px";
    context.canvas.width = width;
    return context.canvas.height = height;
  };

  update = (function() {
    return update = function(dt, entities) {
      var entity, _i, _len, _results;
      _results = [];
      for (_i = 0, _len = entities.length; _i < _len; _i++) {
        entity = entities[_i];
        _results.push(typeof entity.move === "function" ? entity.move(dt) : void 0);
      }
      return _results;
    };
  }).call(this);

  draw = (function() {
    var colour;
    colour = {
      background: "#222222",
      snake: "#EFEFEF"
    };
    return draw = function(context, entities) {
      var entity, _i, _len, _results;
      context.fillStyle = colour.background;
      context.fillRect(0, 0, context.canvas.width, context.canvas.height);
      _results = [];
      for (_i = 0, _len = entities.length; _i < _len; _i++) {
        entity = entities[_i];
        _results.push(entity.draw(context));
      }
      return _results;
    };
  }).call(this);

  getMainLoop = (function(canvas, entities) {
    var context, lastUpdate, mainLoop;
    context = canvas.getContext("2d");
    lastUpdate = (new Date()).getTime();
    return mainLoop = function(fps) {
      var dt, now;
      now = (new Date()).getTime();
      dt = now - lastUpdate;
      lastUpdate = now;
      updateCanvasSize(canvas, context);
      update(dt, entities);
      draw(context, entities);
      if (dt !== 0) {
        document.title = 1000 / dt + " fps";
      }
      return setTimeout(mainLoop, 1 / fps * 1000);
    };
  });

  start = (function() {
    var canvas, entities, handleKeyPress;
    canvas = document.getElementById("canvas");
    entities = [];
    entities.push(new Snake(0.5, 0.5));
    handleKeyPress = function(e) {
      var entity, _i, _len, _results;
      _results = [];
      for (_i = 0, _len = entities.length; _i < _len; _i++) {
        entity = entities[_i];
        _results.push(typeof entity.handleKeyPress === "function" ? entity.handleKeyPress(e.keyCode) : void 0);
      }
      return _results;
    };
    return start = function() {
      canvas.addEventListener("keydown", handleKeyPress, false);
      canvas.focus();
      return getMainLoop(canvas, entities)(1000);
    };
  }).call(this);

  start();

}).call(this);
