// Generated by CoffeeScript 1.6.3
(function() {
  define([], function() {
    var Constant;
    return Constant = (function() {
      function Constant(numerator, denominator) {
        this.numerator = numerator;
        this.denominator = denominator != null ? denominator : 1;
      }

      Constant.prototype.pow = function(power) {
        var _ref;
        if (power < 0) {
          power *= -1;
          _ref = [this.denominator, this.numerator], this.numerator = _ref[0], this.denominator = _ref[1];
        }
        this.numerator = Math.pow(this.numerator, power);
        return this.denominator = Math.pow(this.denominator, power);
      };

      Constant.prototype.copy = function() {
        return new Constant(this.numerator, this.denominator);
      };

      Constant.prototype.toString = function() {
        if (this.denominator === 1) {
          return "" + this.numerator;
        }
        return "" + this.numerator + "/" + this.denominator;
      };

      return Constant;

    })();
  });

}).call(this);
