// Generated by CoffeeScript 1.6.3
(function() {
  define([], function() {
    var Variable;
    return Variable = (function() {
      function Variable(label, power) {
        this.label = label;
        this.power = power != null ? power : 1;
        this.isTerm = true;
        this.isVariable = true;
      }

      Variable.prototype.pow = function(power) {
        return this.power *= power;
      };

      Variable.prototype.copy = function() {
        return new Variable(this.label, this.power);
      };

      Variable.prototype.toString = function() {
        switch (this.power) {
          case 1:
            return this.label;
          case 0:
            return "1";
          default:
            return this.label + "**" + this.power;
        }
      };

      Variable.prototype.toMathML = function() {
        var label, labelArray, labelID, labelOutput;
        labelArray = this.label.split("-");
        label = labelArray[0];
        labelID = labelArray[1] != null ? 'id="variable-' + this.label + '"' : "";
        if (label.length > 1) {
          labelOutput = '<msub class="variable"' + labelID + '><mi>' + label[0] + '</mi><mi>' + label.slice(1) + "</mi></msub>";
        } else {
          labelOutput = '<mi class="variable"' + labelID + '>' + label + '</mi>';
        }
        if (this.power === 1) {
          return labelOutput;
        } else if (this.power > 0) {
          return '<msup>' + labelOutput + '<mn>' + this.power + "</mn></msup>";
        } else {
          return "1";
        }
      };

      return Variable;

    })();
  });

}).call(this);
