// Generated by CoffeeScript 1.6.3
(function() {
  define([], function() {
    var Variable;
    return Variable = (function() {
      function Variable(label, power) {
        this.label = label;
        this.power = power != null ? power : 1;
      }

      Variable.prototype.pow = function(power) {
        return this.power *= power;
      };

      Variable.prototype.copy = function() {
        return new Variable(this.label, this.power);
      };

      Variable.prototype.toString = function() {
        switch (this.power) {
          case 1:
            return this.label;
          case 0:
            return "1";
          default:
            return this.label + "**" + this.power;
        }
      };

      return Variable;

    })();
  });

}).call(this);
