// Generated by CoffeeScript 1.6.3
(function() {
  define(["jquery", "frontend/setEventHandlers", "frontend/settings", "backend/equationIndex", "backend/variableIndex"], function($, setEventHandlers, settings, equationIndex, variableIndex) {
    var addEquationToWhiteboard;
    addEquationToWhiteboard = function(equation, equationID) {
      var equationDiv, html, replacements, variable, _i, _len, _ref;
      replacements = {};
      _ref = equation.getAllVariables();
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        variable = _ref[_i];
        replacements[variable] = variableIndex.getNextUniqueID(variable);
      }
      equation.replaceVariables(replacements);
      if (settings.get("mathJaxEnabled")) {
        html = equation.toMathML(equationID);
        equationDiv = $(html);
        $("#whiteboard-panel").append(equationDiv);
        MathJax.Hub.Queue(["Typeset", MathJax.Hub]);
        return MathJax.Hub.Queue(function() {
          return setEventHandlers(equationDiv);
        });
      } else {
        html = equation.toHTML(equationID);
        equationDiv = $(html);
        $("#whiteboard-panel").append(equationDiv);
        return setEventHandlers(equationDiv);
      }
    };
    return function(equation) {
      var equationID;
      equationID = equationIndex.add(equation);
      addEquationToWhiteboard(equation, equationID);
      return equationID;
    };
  });

}).call(this);
