// Generated by CoffeeScript 1.6.3
(function() {
  define(["jquery", "frontend/setEventHandlers", "frontend/settings", "backend/expressionIndex"], function($, setEventHandlers, settings, expressionIndex) {
    var addExpressionToWhiteboard;
    addExpressionToWhiteboard = function(expression, expressionID) {
      var expressionDiv, html;
      if (settings.get("mathJaxEnabled")) {
        html = expression.toMathML(expressionID, true, "0", true);
        expressionDiv = $(html);
        $("#whiteboard-panel").append(expressionDiv);
        MathJax.Hub.Queue(["Typeset", MathJax.Hub]);
        return MathJax.Hub.Queue(function() {
          return setEventHandlers(expressionDiv);
        });
      } else {
        html = expression.toHTML(expressionID, true, "0", true);
        expressionDiv = $(html);
        $("#whiteboard-panel").append(expressionDiv);
        return setEventHandlers(expressionDiv);
      }
    };
    return function(expression) {
      var expressionID;
      expressionID = expressionIndex.add(expression);
      addExpressionToWhiteboard(expression, expressionID);
      return expressionID;
    };
  });

}).call(this);
