// Generated by CoffeeScript 1.6.3
(function() {
  define(["jquery", "frontend/setDraggables", "frontend/setDoubleClickEvents", "backend/nextExpressionID"], function($, setDraggables, setDoubleClickEvents, nextExpressionID) {
    var addExpression;
    return addExpression = function(expression) {
      var expressionDiv, expressionID, html;
      expressionID = nextExpressionID();
      html = expression.toGEMHTML(expressionID, true);
      expressionDiv = $(html);
      $("#whiteboard-panel").append(expressionDiv);
      setDraggables(expressionDiv);
      return setDoubleClickEvents(expressionDiv);
    };
  });

}).call(this);
