// Generated by CoffeeScript 1.6.3
(function() {
  define(["jquery", "frontend/setDraggables", "frontend/setDoubleClickEvents", "backend/nextEquationID"], function($, setDraggables, setDoubleClickEvents, nextEquationID) {
    var addEquation;
    return addEquation = function(equation) {
      var equationDiv, equationID, html;
      equationID = nextEquationID();
      html = equation.toGEMHTML(equationID);
      equationDiv = $(html);
      $("#whiteboard-panel").append(equationDiv);
      setDraggables(equationDiv);
      return setDoubleClickEvents(equationDiv);
    };
  });

}).call(this);
