// Generated by CoffeeScript 1.6.3
(function() {
  define(["jquery"], function($) {
    return function(comment) {
      var c;
      c = $('<div class="text-comment" />');
      c.text(comment);
      c.html(c.html().replace("\\\\", "<br>"));
      $("#whiteboard-panel").append(c);
      c.draggable({
        containment: "#whiteboard-panel",
        scroll: false
      });
      return c.contextMenu("context-menu-text-comment", {
        "Delete comment": {
          click: function(element) {
            return element.remove();
          }
        },
        "Edit comment": {
          click: function(element) {
            return $.prompt({
              state0: {
                title: "Enter comment.",
                html: '<input type="text" name="comment" value="' + element.html() + '"><br>',
                buttons: {
                  "Okay": 1,
                  "Cancel": -1
                },
                focus: 0,
                submit: function(e, v, m, f) {
                  e.preventDefault();
                  if (v === 1) {
                    element.html(f.comment.replace("\\\\", "<br>"));
                    return $.prompt.close();
                  } else {
                    return $.prompt.close();
                  }
                }
              },
              state1: {
                title: "Please enter a number.",
                buttons: {
                  "Okay": 1,
                  "Cancel": -1
                },
                focus: 0,
                submit: function(e, v, m, f) {
                  e.preventDefault();
                  if (v === 1) {
                    return $.prompt.prevState();
                  } else {
                    return $.prompt.close();
                  }
                }
              }
            });
          }
        }
      }, {
        disable_native_context_menu: true,
        leftClick: false
      });
    };
  });

}).call(this);
