// Generated by CoffeeScript 1.6.3
(function() {
  define(["jquery"], function($) {
    var timeout;
    timeout = 2000;
    return function(element, value) {
      $(element).tooltip({
        content: value,
        items: "*",
        disabled: false,
        hide: {
          effect: "fade",
          duration: timeout / 2,
          delay: timeout
        }
      }).off("mouseover mouseout");
      $(element).tooltip("open");
      return window.setTimeout((function() {
        $(element).tooltip("option", "hide", {
          effect: "fade",
          duration: timeout / 2,
          delay: 0
        });
        $(element).tooltip("close");
        return $(element).tooltip("disable");
      }), timeout);
    };
  });

}).call(this);
