// Generated by CoffeeScript 1.6.3
(function() {
  define(["backend/clearAll", "jquery"], function(clearAll, $) {
    return function() {
      $(".expression").add(".line").add("#whiteboard-panel .equation").remove();
      return clearAll();
    };
  });

}).call(this);
