// Generated by CoffeeScript 1.6.3
(function() {
  define(["jquery"], function($) {
    return function() {
      $("#gem-window").show();
      $("#loader").hide();
      return window.loadedGEM = true;
    };
  });

}).call(this);
