// Generated by CoffeeScript 1.6.3
(function() {
  define(["jquery"], function($) {
    var finishLoading;
    return finishLoading = function() {
      $("#gem-window").show();
      return $("#loader").hide();
    };
  });

}).call(this);
