// Generated by CoffeeScript 1.6.3
(function() {
  define(function() {
    return function(name) {
      if ((name = (new RegExp('[?&]' + encodeURIComponent(name) + '=([^&]*)')).exec(location.search))) {
        return decodeURIComponent(name[1]);
      }
    };
  });

}).call(this);
