// Generated by CoffeeScript 1.6.3
(function() {
  define(["frontend/addEquation", "backend/formulae"], function(addEquation, formulae) {
    return function(left, right) {
      var equation, equationID;
      equation = formulae.makeEquation(left, right);
      equationID = addEquation(equation);
      return [equationID, equation];
    };
  });

}).call(this);
