// Generated by CoffeeScript 1.6.3
(function() {
  define(["jquery"], function($) {
    var setDraggables;
    return setDraggables = function(element) {
      var draggableProperties;
      draggableProperties = {
        containment: "#whiteboard-panel",
        scroll: false,
        cancel: ".variable"
      };
      if (element != null) {
        return element.draggable(draggableProperties);
      } else {
        $(".equation").draggable(draggableProperties);
        return $(".expression").draggable(draggableProperties);
      }
    };
  });

}).call(this);
