// Generated by CoffeeScript 1.6.3
(function() {
  define(["jquery", "require"], function($, require) {
    var setDoubleClickEvents;
    return setDoubleClickEvents = function(element) {
      var target;
      if (element != null) {
        target = $(element).children(".variable");
      } else {
        target = $(".variable");
      }
      target.dblclick(function() {
        var formulaID, formulaNumber, formulaType, variable, _ref;
        variable = $(this).text();
        formulaID = $(this).parent().attr("id");
        _ref = formulaID.split("-"), formulaType = _ref[0], formulaNumber = _ref[1];
        console.log("Double-clicked " + variable + " in " + formulaType + " " + formulaNumber);
        if (formulaType === "equation") {
          return require(["backend/solveEquation", "frontend/addExpressionToWhiteboard", "backend/addExpressionToIndex"], function(solveEquation, addExpressionToWhiteboard, addExpressionToIndex) {
            var expression;
            expression = solveEquation(formulaNumber, variable);
            addExpressionToWhiteboard(expression);
            return addExpressionToIndex(expression);
          });
        }
      });
      return target.disableSelection();
    };
  });

}).call(this);
