// Generated by CoffeeScript 1.6.3
(function() {
  define(["jquery", "require"], function($, require) {
    var setDoubleClickEvents, setEquationDraggables, setVariableDraggables;
    setEquationDraggables = function(element) {
      var draggableProperties;
      if (element == null) {
        element = null;
      }
      draggableProperties = {
        containment: "#whiteboard-panel",
        scroll: false,
        cancel: ".variable"
      };
      if (element != null) {
        return element.draggable(draggableProperties);
      } else {
        $(".equation").draggable(draggableProperties);
        return $(".expression").draggable(draggableProperties);
      }
    };
    setDoubleClickEvents = function(element) {
      var target;
      if (element == null) {
        element = null;
      }
      if (element != null) {
        target = $(element).find(".variable");
      } else {
        target = $(".variable");
      }
      target.doubletap(function() {
        var formulaID, formulaNumber, formulaType, variable, _ref;
        variable = $(this).text();
        formulaID = $(this).parents("div").attr("id");
        _ref = formulaID.split("-"), formulaType = _ref[0], formulaNumber = _ref[1];
        console.log("Double-clicked " + variable + " in " + formulaType + " " + formulaNumber);
        if (formulaType === "equation") {
          return require(["backend/solveEquation", "frontend/addExpression"], function(solveEquation, addExpression) {
            var expression;
            expression = solveEquation(formulaNumber, variable);
            return addExpression(expression);
          });
        }
      });
      return target.disableSelection();
    };
    setVariableDraggables = function(element) {
      var target;
      if (element == null) {
        element = null;
      }
      if (element != null) {
        target = $(element).find(".variable");
      } else {
        target = $(".variable");
      }
      return target.draggable({
        start: function(event, ui) {
          $(ui.helper).addClass("equationVariableHelper");
          $(ui.helper).css("font-size", $(event.target).css("font-size"));
          return $(event.target).fadeTo(0, 0);
        },
        drag: function(event, ui) {},
        stop: function(event, ui) {
          return $(event.target).fadeTo(0, 1);
        },
        containment: "#whiteboard-panel",
        revert: true,
        helper: "clone",
        appendTo: "#whiteboard-panel"
      });
    };
    return function(element) {
      if (element == null) {
        element = null;
      }
      setEquationDraggables(element);
      setDoubleClickEvents(element);
      return setVariableDraggables(element);
    };
  });

}).call(this);
