// Generated by CoffeeScript 1.6.3
(function() {
  define(["jquery", "frontend/addTextComment", "frontend/updateSearchResults", "frontend/settings", "frontend/clearAll", "require"], function($, addTextComment, updateSearchResults, settings, clearAll, require) {
    return function() {
      $("#extra-add-comment").click(function() {
        return $.prompt({
          state0: {
            title: "Enter comment.",
            html: '<input type="text" name="comment" value="Physics is great"><br>',
            buttons: {
              "Okay": 1,
              "Cancel": -1
            },
            focus: "input[name='comment']",
            submit: function(e, v, m, f) {
              var comment;
              e.preventDefault();
              if (v === 1) {
                comment = f.comment;
                addTextComment(comment);
              }
              return $.prompt.close();
            }
          }
        });
      });
      $("#extra-uncertainties").click(function() {
        $(this).toggleClass("button-down");
        settings.set("showSymbolicUncertainties", !settings.get("showSymbolicUncertainties"));
        settings.set("assumeZeroUncertainty", !settings.get("assumeZeroUncertainty"));
        return require(["frontend/rewrite"], function(rewrite) {
          return rewrite.refreshExpressions();
        });
      });
      $("#extra-clear").click(function() {
        return clearAll();
      });
      return $("#search-box").on("change keyup paste", function() {
        var condition;
        condition = function(z) {
          return (new RegExp($("#search-box").val())).test(z);
        };
        return updateSearchResults(condition);
      });
    };
  });

}).call(this);
