// Generated by CoffeeScript 1.6.3
(function() {
  define(["jquery", "backend/getFormulae", "frontend/addEquationToWhiteboard", "backend/addEquationToIndex"], function($, getFormulae, addEquationToWhiteboard, addEquationToIndex) {
    var setSearchClick;
    return setSearchClick = function(element) {
      var target;
      if (element != null) {
        target = element;
      } else {
        target = $(".search-result");
      }
      return target.click(function() {
        var equation, equationName;
        equationName = $(this).attr("id");
        console.log(equationName);
        equation = getFormulae()[equationName];
        addEquationToWhiteboard(equation);
        return addEquationToIndex(equation);
      });
    };
  });

}).call(this);
