// Generated by CoffeeScript 1.6.3
(function() {
  define(["jquery", "backend/formulae", "frontend/addEquation"], function($, formulae, addEquation) {
    var initialised;
    initialised = false;
    return function(element) {
      var target;
      if (element == null) {
        element = null;
      }
      if (element != null) {
        target = element;
      } else {
        target = $(".search-result");
      }
      if (!initialised) {
        $("#whiteboard-panel").droppable({
          tolerance: "pointer",
          accept: ".search-result",
          drop: function(event, ui) {
            var equation, equationName;
            equationName = $(ui.draggable).attr("id").split("-").slice(1).join("-");
            equation = formulae.get(equationName);
            return addEquation(equation, ui.position);
          }
        });
        initialised = true;
      }
      target.click(function() {
        var equation, equationName;
        equationName = $(this).attr("id").split("-").slice(1).join("-");
        equation = formulae.get(equationName);
        return addEquation(equation);
      });
      return target.draggable({
        helper: "clone",
        appendTo: "#whiteboard-panel"
      });
    };
  });

}).call(this);
