// Generated by CoffeeScript 1.6.3
(function() {
  define(["jquery", "backend/getFormula", "frontend/addEquation"], function($, getFormula, addEquation) {
    return function(element) {
      var target;
      if (element == null) {
        element = null;
      }
      if (element != null) {
        target = element;
      } else {
        target = $(".search-result");
      }
      return target.click(function() {
        var equation, equationName;
        equationName = $(this).attr("id");
        equation = getFormula(equationName);
        return addEquation(equation);
      });
    };
  });

}).call(this);
