// Generated by CoffeeScript 1.6.3
(function() {
  define(["frontend/getParameter", "frontend/settings"], function(getParameter, settings) {
    return function() {
      var g, key, _i, _len, _ref, _results;
      console.log("Loading settings...");
      _ref = settings.keys();
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        key = _ref[_i];
        g = getParameter(key);
        if (g != null) {
          if (g === "false") {
            g = false;
          } else if (g === "true") {
            g = true;
          }
          settings.set(key, g);
        }
        _results.push(console.log(key, settings.get(key)));
      }
      return _results;
    };
  });

}).call(this);
