// Generated by CoffeeScript 1.6.3
(function() {
  define(["jquery", "frontend/setEventHandlers", "frontend/setSearchResultHandlers"], function($, setEventHandlers, setSearchResultHandlers) {
    return function() {
      setEventHandlers();
      return setSearchResultHandlers();
    };
  });

}).call(this);
