// Generated by CoffeeScript 1.6.3
(function() {
  define(["jquery", "frontend/solveEquation", "frontend/setDraggables", "frontend/setDoubleClickEvents"], function($, solveEquation, setDraggables, setDoubleClickEvents) {
    var setupFrontend;
    return setupFrontend = function() {
      setDraggables();
      return setDoubleClickEvents();
    };
  });

}).call(this);
