// Generated by CoffeeScript 1.6.3
(function() {
  define(["jquery", "frontend/setEventHandlers", "frontend/setSearchResultHandlers", "frontend/connections"], function($, setEventHandlers, setSearchResultHandlers, connections) {
    return function() {
      $(window).resize(function() {
        return connections.repaintVariables();
      });
      setEventHandlers();
      return setSearchResultHandlers();
    };
  });

}).call(this);
