// Generated by CoffeeScript 1.6.3
(function() {
  define(["jquery", "frontend/setDraggables", "frontend/setDoubleClickEvents"], function($, setDraggables, setDoubleClickEvents) {
    var solveEquation;
    return solveEquation = function(equationID, variable) {
      $("#whiteboard-panel").append('<div id="expression-2" class="expression"><span class="variable">' + variable + '</span>' + ' = <span class="variable">' + variable + '</span></div>');
      setDraggables($("#expression-2"));
      return setDoubleClickEvents($("#expression-2"));
    };
  });

}).call(this);
