// Generated by CoffeeScript 1.6.3
(function() {
  define(["jquery", "frontend/setDraggables", "frontend/setDoubleClickEvents", "backend/solveEquation", "backend/getExpressions"], function($, setDraggables, setDoubleClickEvents, doSolveEquation, getExpressions) {
    var solveEquation;
    return solveEquation = function(equationID, variable) {
      var newExpressionID;
      newExpressionID = getExpressions().length;
      $("#whiteboard-panel").append('<div id="expression-' + newExpressionID + '" class="expression"><span class="variable">' + variable + '</span>' + ' = <span class="variable">' + variable + '</span></div>');
      getExpressions().push("expression we don't care about");
      setDraggables($("#expression-" + newExpressionID));
      return setDoubleClickEvents($("#expression-" + newExpressionID));
    };
  });

}).call(this);
