// Generated by CoffeeScript 1.6.3
(function() {
  define(["jquery", "frontend/rewrite", "backend/substituteEquation", "backend/equationIndex", "backend/expressionIndex"], function($, rewrite, substituteEquation, equationIndex, expressionIndex) {
    return function(targetExpressionID, sourceEquationID, variableID) {
      var sourceEquation, subbedEquation, targetExpression;
      targetExpression = expressionIndex.get(targetExpressionID);
      sourceEquation = equationIndex.get(sourceEquationID);
      subbedEquation = substituteEquation(targetExpression, sourceEquation, variableID);
      return rewrite.rewriteExpression(targetExpressionID, subbedEquation);
    };
  });

}).call(this);
