// Generated by CoffeeScript 1.6.3
(function() {
  define(["jquery", "backend/formulae", "frontend/settings", "frontend/setSearchResultHandlers"], function($, formulae, settings, setSearchResultHandlers) {
    return function(condition) {
      var formula, _i, _len, _ref;
      $("#search-results ul").empty();
      _ref = formulae.getAllFormulaNames();
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        formula = _ref[_i];
        if ((condition == null) || condition(formula)) {
          $("#search-results ul").append($('<li id="formula-' + formula + '" class="search-result">' + formulae.get(formula).toMathML(null, false, "0", true) + '</li>'));
        }
      }
      if (settings.get("mathJaxEnabled")) {
        MathJax.Hub.Queue(["Typeset", MathJax.Hub]);
        return MathJax.Hub.Queue(function() {
          return setSearchResultHandlers();
        });
      } else {
        return setSearchResultHandlers();
      }
    };
  });

}).call(this);
