// Generated by CoffeeScript 1.6.3
(function() {
  define(["backend/getEquations"], function(getEquations) {
    var addEquation;
    return addEquation = function(equation) {
      return getEquations().push(equation);
    };
  });

}).call(this);
