// Generated by CoffeeScript 1.6.3
(function() {
  define(["backend/getEquations"], function(getEquations) {
    var addEquationToIndex;
    return addEquationToIndex = function(equation) {
      return getEquations().push(equation);
    };
  });

}).call(this);
