// Generated by CoffeeScript 1.6.3
(function() {
  define(["backend/getExpressions"], function(getExpressions) {
    var addExpression;
    return addExpression = function(expression) {
      return getExpressions().push(expression);
    };
  });

}).call(this);
