// Generated by CoffeeScript 1.6.3
(function() {
  define(function() {
    var expressions;
    expressions = [];
    return {
      add: function(expression) {
        expressions.push(expression);
        return expressions.length - 1;
      },
      get: function(expressionID) {
        if (expressionID >= expressions.length || expressionID < 0) {
          throw new Error("No expression with ID " + expressionID + " exists.");
        }
        return expressions[expressionID];
      },
      size: function() {
        return expressions.length;
      },
      set: function(expressionID, expression) {
        if (expressionID >= expression.length || expressionID < 0) {
          throw new Error("No expression with ID " + expressionID + " exists.");
        }
        expressions[expressionID] = expression;
        return expressions[expressionID];
      },
      clear: function() {
        return expressions.splice(0);
      }
    };
  });

}).call(this);
