// Generated by CoffeeScript 1.6.3
(function() {
  define(["JSAlgebra/equation"], function(Equation) {
    var formulae;
    formulae = {
      "kinetic-energy": new Equation(["Ek"], ["1/2", "m", "v**2"]),
      "momentum": new Equation(["p"], ["m", "v"]),
      "gravity": new Equation(["F"], ["G", "m", "M", "r**-2"]),
      "gravitational-potential-energy": new Equation(["Ep"], ["-1", "G", "m", "M", "r**-1"])
    };
    return function() {
      return formulae;
    };
  });

}).call(this);
