// Generated by CoffeeScript 1.6.3
(function() {
  define(["coffeequate"], function(coffeequate) {
    var formulae;
    formulae = {
      "kinetic-energy": function() {
        return new coffeequate.Equation("Ek", "m * v**2 * 1/2");
      },
      "momentum": function() {
        return new coffeequate.Equation("p", "m * v");
      },
      "gravity": function() {
        return new coffeequate.Equation("F", "\\G * m * M * r**-2");
      },
      "gravitational-potential-energy": function() {
        return new coffeequate.Equation("Ep", "-1 * \\G * m * M * r**-1");
      },
      "gravitational-potential-energy-simple": function() {
        return new coffeequate.Equation("Ep", "m * g * h");
      },
      "force": function() {
        return new coffeequate.Equation("F", "m * a");
      },
      "centripetal-force": function() {
        return new coffeequate.Equation("F", "m * v**2 * r**-1");
      },
      "product": function() {
        return new coffeequate.Equation("a", "b * c");
      },
      "contrived-pow-example": function() {
        return new coffeequate.Equation("a", "(b**-1)");
      },
      "projectile-motion": function() {
        return new coffeequate.Equation("s", "u * t + 1/2 * a * t**2");
      },
      "energy-mass-relation": function() {
        return new coffeequate.Equation("E", "m * \\c ** 2");
      }
    };
    return function(name) {
      if (name in formulae) {
        return formulae[name]();
      } else {
        throw new Error("No formula called " + name + " exists.");
      }
    };
  });

}).call(this);
