// Generated by CoffeeScript 1.6.3
(function() {
  define(["backend/getEquations"], function(getEquations) {
    var nextEquationID;
    return nextEquationID = function() {
      return getEquations().length;
    };
  });

}).call(this);
