// Generated by CoffeeScript 1.6.3
(function() {
  define(["backend/getExpressions"], function(getExpressions) {
    var nextExpressionID;
    return nextExpressionID = function() {
      return getExpressions().length;
    };
  });

}).call(this);
