// Generated by CoffeeScript 1.6.3
(function() {
  define(function() {
    var valueExpressions, values;
    values = {};
    valueExpressions = {};
    return {
      set: function(variable, value, expr) {
        values[variable] = value;
        return valueExpressions[variable] = expr;
      },
      get: function(variable) {
        if (variable in values) {
          return value[variable];
        } else {
          return null;
        }
      },
      getExpression: function(variable) {
        return valueExpressions[variable];
      },
      getNumericalValues: function() {
        return values;
      }
    };
  });

}).call(this);
