// Generated by CoffeeScript 1.6.3
(function() {
  define(function() {
    var valueExpressions, values;
    values = {};
    valueExpressions = {};
    return {
      set: function(variable, value, expr) {
        values[variable] = value;
        return valueExpressions[variable] = expr;
      },
      get: function(variable) {
        if (variable in values) {
          return values[variable];
        } else {
          return null;
        }
      },
      getExpression: function(variable) {
        return valueExpressions[variable];
      },
      getNumericalValues: function() {
        return values;
      },
      clear: function() {
        var prop, _results;
        for (prop in values) {
          if (values.hasOwnProperty(prop)) {
            delete values[prop];
          }
        }
        _results = [];
        for (prop in valueExpressions) {
          if (valueExpressions.hasOwnProperty(prop)) {
            _results.push(delete valueExpressions[prop]);
          } else {
            _results.push(void 0);
          }
        }
        return _results;
      }
    };
  });

}).call(this);
