// Generated by CoffeeScript 1.6.3
(function() {
  define(["backend/getEquations"], function(getEquations) {
    var solveEquation;
    return solveEquation = function(equationID, variable) {
      var equation;
      equation = getEquations()[equationID];
      return equation.solve(variable);
    };
  });

}).call(this);
