// Generated by CoffeeScript 1.6.3
(function() {
  define(["backend/equivalenciesIndex"], function(equivalenciesIndex) {
    return function(targetEquation, sourceExpression, variable) {
      return targetEquation.substituteExpression(sourceExpression, variable, equivalenciesIndex);
    };
  });

}).call(this);
