// Generated by CoffeeScript 1.6.3
(function() {
  define(["backend/equivalenciesIndex"], function(equivalenciesIndex) {
    return function(targetEquation, sourceEquation, variable) {
      return targetEquation.substituteEquation(sourceEquation, variable, equivalenciesIndex);
    };
  });

}).call(this);
